server:
  port: ${PORT:8080}

spring:
  profiles:
    active: local
  data:
    web:
      pageable:
        size-parameter: limit
        one-indexed-parameters: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: user_service_schema
  flyway:
    default-schema: user_service_schema
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
